services:
  - type: web
    name: white-whaling-server
    runtime: node
    buildCommand: npm install
    startCommand: node index.js
    rootDirectory: server
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: CLIENT_URL
        sync: false  # You'll set this to your Netlify URL
